<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

 $GLOBALS['TL_LANG']['MOD']['form_google_recaptcha'] = 'Google Recaptcha form field';
 $GLOBALS['TL_LANG']['FFL']['google_recaptcha'][0] = 'Google reCAPTCHA';
 $GLOBALS['TL_LANG']['FFL']['google_recaptcha'][1] = 'Validate users with the "I am not a robot" checkbox.';