<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
 $GLOBALS['TL_LANG']['tl_form_field']['google_recaptcha_placeholder'][0] = 'Site Key';
 $GLOBALS['TL_LANG']['tl_form_field']['google_recaptcha_placeholder'][1] = 'Use this key in the HTML code for the users of your website. Request key: <a target="_blank" href="https://www.google.com/recaptcha">https://www.google.com/recaptcha</a>';
 $GLOBALS['TL_LANG']['tl_form_field']['google_recaptcha_slabel'][0] = 'Secret Key';
 $GLOBALS['TL_LANG']['tl_form_field']['google_recaptcha_slabel'][1] = 'Use this key for communication between your website and Google. Keep this key secret. Request key: <a target="_blank" href="https://www.google.com/recaptcha">https://www.google.com/recaptcha</a>';