<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MOD']['form_google_recaptcha'] 		= 'Google Recaptcha Formularfeld';
$GLOBALS['TL_LANG']['FFL']['google_recaptcha'][0] 			= 'Google reCAPTCHA';
$GLOBALS['TL_LANG']['FFL']['google_recaptcha'][1] 			= 'Nutzer mit dem Kästchen "Ich bin kein Roboter" validieren.';
$GLOBALS['TL_LANG']['FFL']['google_recaptcha_hidden'][0] 	= 'Google reCAPTCHA [unsichtbar, Absendebutton]';
$GLOBALS['TL_LANG']['FFL']['google_recaptcha_hidden'][1] 	= 'Nutzer im Hintergrund validieren';
